# Generated by Django 5.0.6 on 2024-05-30 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assignments', '0002_delete_controlwork_delete_homework_delete_theory_and_more'),
        ('courses', '0002_course_end_date_course_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments',
                                    to='courses.course'),
        ),
        migrations.CreateModel(
            name='SubmittedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submitted_assignments/')),
                ('assignment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                (
                    'student',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
