# Generated by Django 5.0.6 on 2024-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_submittedassignment_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassignment',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
