# Generated by Django 5.0.6 on 2024-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_submittedassignment_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='submitted_on_time',
            field=models.BooleanField(default=True),
        ),
    ]
