# Generated by Django 5.0.6 on 2024-05-30 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_submittedassignment_submitted_on_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassignment',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
