# Generated by Django 5.0.6 on 2024-05-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_assignment_file_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
