# Generated by Django 5.0.6 on 2024-06-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_assignment_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittedassignment',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
