# Generated by Django 5.0.6 on 2024-06-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_testquestion_answeroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('homework', 'Домашняя работа'), ('theory', 'Теория'), ('controlwork', 'Контрольная работа'), ('test', 'Тест')], max_length=20),
        ),
    ]
