# Generated by Django 5.0.6 on 2024-06-12 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_assignment_damage_assignment_max_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassignment',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
