# Generated by Django 5.0.6 on 2024-06-12 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_end_date_course_start_date'),
        ('gamification', '0002_character_default_avatar_alter_character_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.character')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'unique_together': {('character', 'course')},
            },
        ),
    ]
