# Generated by Django 5.0.6 on 2024-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
